services:
  user-mgmt:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gakuren-network"
      - "traefik.http.routers.user-mgmt.rule=PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.user-mgmt.entrypoints=web"
      - "traefik.http.services.user-mgmt.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      gakuren-network:
        aliases:
          - user-mgmt

networks:
  gakuren-network:
    external: true