services:
  user-mgmt:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-mgmt.rule=PathPrefix(`/`)"
      - "traefik.http.routers.user-mgmt.entrypoints=gakuren-network"
      - "traefik.http.routers.user-mgmt.service=user-mgmt-svc"
      - "traefik.http.services.user-mgmt-svc.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      - gakuren-network

networks:
  gakuren-network:
    external: true